### ISSUE TITLE
timewarp bug

### ISSUE THREAD

**Issue by Stardom-game** [Stardom-game/Stardom#10]
cant  timewarp properly after like 20 uses it breaks

Traceback (most recent call last):
  File "C:\Users\denis\Downloads\Stardom-master\Stardom-main\main.py", line 31, in <module>
    physics.lerp_angular_velocity()
  File "C:\Users\denis\Downloads\Stardom-master\Stardom-main\variables_functions\physics.py", line 425, in lerp_angular_velocity
    match_grav_accel(block[1], i)
  File "C:\Users\denis\Downloads\Stardom-master\Stardom-main\variables_functions\physics.py", line 265, in match_grav_accel
    obj.body.position = variables.trajectory_follows[str(obj_index)][0], variables.trajectory_follows[str(obj_index)][1]
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'int' object is not subscriptable

**Comment by VeryCrazyCat** [comment]
fixed 31/10/24 3pm
