### ISSUE TITLE
cannot close window with X only with ctrl+C

### ISSUE THREAD

**Issue by Stardom-game** [Stardom-game/Stardom#12]
Traceback (most recent call last):
  File "C:\Users\denis\Downloads\Stardom-master\Stardom-main\main.py", line 33, in <module>
    planets.update()
  File "C:\Users\denis\Downloads\Stardom-master\Stardom-main\variables_functions\planets.py", line 10, in update
    planet.update()
  File "C:\Users\denis\Downloads\Stardom-master\Stardom-main\variables_functions\planet.py", line 21, in update
    zoomer.blit_zoom(pygame.transform.scale(self.image, (self.radius*2, self.radius*2)), (self.rect.x - self.radius, self.rect.y - self.radius))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

**Bug after force closing the window**

**Comment by Fluffik3666** [comment]
ill take over

**Comment by Fluffik3666** [comment]
fixed
